purchase5assigniment
lanrecoal2020/AutoTest pull request #4
Opened 2021-02-02 12:52 UTC by PrinceItam

2021-02-02 13:03 UTC, bidemi20002000 approved these changes

2021-02-03 15:19 UTC, bidemi20002000 commented
Hello Prince, your Test did not inherit the common steps. Our framework is design such that every test should inherit the common steps.
secondly, your assertion appears to be pointing to home page rather than confirm that the order was successful

2021-02-03 15:27 UTC, lanrecoal2020 requested changes
Your test is not pointed to test base at all. If there is a test base configured for the project, then all tests within the project should be pointing to testbase. See the commontest,java file to see how you use testbase and config properties variables to navigate to homepage.

2021-02-03 15:33 UTC, lanrecoal2020 commented
@PrinceItam NB.When you point ur test to testbase, you dont need to declare public Webdrive driver in your step definition file. see commonTest.java and see how you can us the @before annotation to innitialize the webdriver that is declared in testbase

2021-02-03 21:08 UTC, PrinceItam commented
Changes made please review

2021-02-03 21:36 UTC, lanrecoal2020 requested changes

2021-02-03 21:36 UTC, lanrecoal2020 commented on src/test/java/Step_Definition/purchase5.java
> +        driver.findElement(By.id("quantity_wanted")).sendKeys("65");
please change lines 44 and 45 to page object format

2021-02-03 21:36 UTC, lanrecoal2020 commented on src/test/java/Step_Definition/purchase5.java
>          String ExpectedMessage = "ORDER HISTORY";
Please assert your successful order with the success message. This order history doesnt really confirm the order that the last test run made...

2021-02-04 18:52 UTC, lanrecoal2020 approved these changes

2021-02-04 20:50 UTC, merged