Purchase4
lanrecoal2020/AutoTest pull request #7
Opened 2021-02-03 08:13 UTC by egbeteok

Purchase4 Test.

2021-02-03 08:27 UTC, fadeosun reviewed
Acknowledged

2021-02-03 15:23 UTC, lanrecoal2020 requested changes
Your test is not pointed to test base at all. If there is a test base configured for the project, then all tests within the project should be pointing to testbase. See the commontest,java file to see how you use testbase and config properties variables to navigate to homepage.

2021-02-04 10:31 UTC, lanrecoal2020 approved these changes

2021-02-04 19:07 UTC, fadeosun approved these changes
good job

2021-02-06 12:54 UTC, merged